version: '3.8'
services:
  database:
    image: mysql:5.7
    container_name: service_database
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    restart: on-failure
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=C4l4ng3@P4SsW0rd
      - MYSQL_ROOT_PASSWORD=4dm1n#C4l4ng3@P4SsW0rd
      - MYSQL_DATABASE=transaction

volumes:
  database: