version: '3.8'
services:
  database:
    image: mysql:5.7
    container_name: service_database
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: on-failure
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD_ADM}
      - MYSQL_DATABASE=${DATABASE_NAME}
    networks:
      - challenge

  api:
    image: transaction:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - database
    networks:
      - challenge
    environment:
      - DATABASE_SERVER_URL=${DATABASE_SERVER_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

volumes:
  database:

networks:
  challenge:
    driver: bridge
